project:
  type: website
  output-dir: docs
  resources:
    - .nojekyll

website:
  title: "Shokhrukhkhon Nishonkulov"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: publications.qmd
        text: Publications
      - href: blog.qmd
        text: Blog
      - href: cv.qmd
        text: CV
      - href: contact.qmd
        text: Contact
    right:
      - icon: github
        href: https://github.com/mrshohruh
        aria-label: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/shokhrukhkhon-nishonkulov-b70250210?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app
        aria-label: LinkedIn
      - icon: telegram
        href: https://t.me/Iqtisodchiroq
        aria-label: Telegram

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
